version: '3'

services:
  frontend:
    image: angular-cli-docker-ootb
    build: .
    environment:
      NODE_ENV: production
    ports:
      - 4200:4200
    command: [nginx-debug, '-g', 'daemon off;']
